version: "3.7"
services:
  en_php:
    build:
      context: ./
      dockerfile: docker/config/Dockerfile-php
    container_name: ${PROJECT_NAME}_php
    image: ${PROJECT_NAME}_php
    user: $UID:$GID
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/common/php.ini:/usr/local/etc/php/php.ini
    environment:
      COMPOSER_MEMORY_LIMIT: 2G
      XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST} client_port=${XDEBUG_STORM_PORT} remote_enable=1
      PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
    network_mode: host
    depends_on:
      - en_db
  en_db:
    image: 'mysql:8.0'
    container_name: ${PROJECT_NAME}_db
    user: $UID:$GID
    ports:
      - ${DB_LOCAL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './sailmysql:/var/lib/mysql'
      - './docker/common/mysql:/etc/mysql/conf.d'
    network_mode: host
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
  en_nginx:
    image: nginx:1.17-alpine
    user: $UID:$GID
    restart: unless-stopped
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - ${NGINX_LOCAL_PORT}:80
    volumes:
      - ./:/var/www
      - ./logs:/logs
      - ./docker/common/host.conf:/etc/nginx/conf.d/default.conf
      - ./docker/common/.htpasswd:/etc/nginx/.htpasswd
    network_mode: host
    depends_on:
      - en_php
